### Introduction to Pandas (Python DataFrames)

In [1]:
# how to create a dataframe
import pandas as pd
import numpy  as np
df = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6]]))
print(df)
print(df.shape)
print(df.index)
df.columns=["a","b","c"]
print(df.columns.values)
print(df)
indexlist = ["row_"+str(i) for i in range(0,2)]
df.index = indexlist
print(df)

   0  1  2
0  1  2  3
1  4  5  6
(2, 3)
RangeIndex(start=0, stop=2, step=1)
['a' 'b' 'c']
   a  b  c
0  1  2  3
1  4  5  6
       a  b  c
row_0  1  2  3
row_1  4  5  6

In [2]:
# how to access a row or column by name
print(df.loc['row_1',:])
print(df.loc[:,'b'])
# or by index
print(df.iloc[1,:])
print(df.iloc[:,1])

a    4
b    5
c    6
Name: row_1, dtype: int32
row_0    2
row_1    5
Name: b, dtype: int32
a    4
b    5
c    6
Name: row_1, dtype: int32
row_0    2
row_1    5
Name: b, dtype: int32

In [3]:
# accessing individual elements
# by row and column name
print(df.loc['row_1','b'])
# or by index
print(df.iloc[0,1])

5
2

In [4]:
# adding a column
df['d']=[89,90]
print(df)

       a  b  c   d
row_0  1  2  3  89
row_1  4  5  6  90

In [9]:
# adding a row
one=pd.DataFrame(np.array([[33,34,35,36]]))
one.columns=df.columns
one.index=["row_2"]
df2=pd.concat([df,one])
print(df2)

        a   b   c   d
row_0   1   2   3  89
row_1   4   5   6  90
row_2  33  34  35  36

In [72]:
# dropping columns
df2.loc[:,'e'] = pd.Series(['51', '61','71'], index=df2.index)
df2.drop('c', axis=1, inplace=True)
print(df2)
df2.drop(df2.columns[1],axis=1,inplace=True)
print(df2)

        a   b   d   e
row_0   1   2  89  51
row_1   4   5  90  61
row_2  33  34  36  71
        a   d   e
row_0   1  89  51
row_1   4  90  61
row_2  33  36  71

In [74]:
# dropping rows
print(df2)
df3=df2.drop(df2.index[1])
print(df3)

        a   d   e
row_0   1  89  51
row_1   4  90  61
row_2  33  36  71
        a   d   e
row_0   1  89  51
row_2  33  36  71

In [75]:
# renaming columns and index
df3.columns=['A','B','C']
df3.index=[0,1]
print(df3)

    A   B   C
0   1  89  51
1  33  36  71

In [89]:
z = pd.DataFrame(np.array([[1, 2, 3],[4, 5, 6],[7,8,9]]))
z.columns=["a","b","c"]
z.index = [i for i in range(0,3)]
print(z)
# select rows based on selected elements of a column
sel = z['a']>=4
z[sel]

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

   a  b  c
1  4  5  6
2  7  8  9

In [151]:
# create a data frame with NaN's
df = pd.DataFrame(index=range(0,4),columns=['A','B'], dtype='float')
print(df)
# create a data frame with value 1.0
df = pd.DataFrame(1,index=range(0,4),columns=['A','B'], dtype='float')
# set row 1 to [2,3]
df.loc[1]=[2,3]
print(df)
# and apply a lambda to multiply all values with 2
df.apply(lambda x: x*2)

    A   B
0 NaN NaN
1 NaN NaN
2 NaN NaN
3 NaN NaN
     A    B
0  1.0  1.0
1  2.0  3.0
2  1.0  1.0
3  1.0  1.0

     A    B
0  2.0  2.0
1  4.0  6.0
2  2.0  2.0
3  2.0  2.0

In [90]:
# writing a data frame to a (tab-delimited) file
LETTERS = [chr(i) for i in range(65,65+26)]
# letters = [chr(i) for i in range(97,97+26)]
# print(LETTERS)
# print(letters)
x = np.random.random((100,26))
z = pd.DataFrame(data=x, columns=LETTERS)
# print(z)
z.to_csv('z100x26.txt', sep='\t')

           A         B         C         D         E         F         G  \
0   0.278071  0.740804  0.925906  0.367537  0.214324  0.262283  0.543779
1   0.679101  0.353416  0.965890  0.288304  0.836071  0.214951  0.444700
2   0.945715  0.279901  0.438485  0.224500  0.171580  0.516699  0.892480
3   0.282437  0.293052  0.146134  0.290180  0.268977  0.566643  0.558605
4   0.589821  0.273693  0.286441  0.015402  0.123820  0.817337  0.282559
5   0.392515  0.227871  0.530259  0.946504  0.907158  0.706957  0.546290
6   0.372466  0.036393  0.406320  0.402558  0.151619  0.022904  0.560205
7   0.988781  0.988428  0.307309  0.357146  0.343865  0.498124  0.121418
8   0.283421  0.718084  0.244823  0.492925  0.854933  0.260757  0.058170
9   0.074840  0.267225  0.794192  0.043674  0.477426  0.684972  0.755390
10  0.805960  0.937869  0.322819  0.199484  0.822056  0.873693  0.072740
11  0.048046  0.894130  0.780798  0.399268  0.593345  0.539359  0.505126
12  0.139786  0.876787  0.382417  0.136575  0.616924  0.614759  0.989816
13  0.908806  0.265563  0.903739  0.667861  0.382554  0.038910  0.903628
14  0.445683  0.773835  0.443605  0.241124  0.210210  0.169207  0.481268
15  0.863906  0.308854  0.185175  0.693204  0.018189  0.290168  0.075135
16  0.493259  0.436608  0.934674  0.912828  0.129333  0.114344  0.084894
17  0.317238  0.320051  0.726600  0.888456  0.200346  0.082695  0.188111
18  0.056751  0.751209  0.850419  0.897143  0.834117  0.365878  0.265956
19  0.158869  0.987947  0.342089  0.576019  0.089543  0.769612  0.056983
20  0.810642  0.094862  0.850310  0.198395  0.003733  0.831462  0.859046
21  0.937844  0.607841  0.813079  0.351497  0.691352  0.479742  0.069275
22  0.932496  0.626541  0.539008  0.714612  0.072446  0.904214  0.331032
23  0.337198  0.498901  0.436769  0.541416  0.197878  0.649528  0.922232
24  0.242568  0.828603  0.312151  0.971651  0.026583  0.507897  0.654052
25  0.940278  0.053072  0.660811  0.280208  0.168743  0.499549  0.351120
26  0.850372  0.780843  0.632208  0.764150  0.138133  0.184070  0.949352
27  0.107491  0.324565  0.133871  0.455626  0.643841  0.456326  0.882961
28  0.427050  0.608492  0.508234  0.860842  0.089094  0.885455  0.921941
29  0.706728  0.139168  0.875368  0.333395  0.040671  0.019054  0.639497
..       ...       ...       ...       ...       ...       ...       ...
70  0.726469  0.362957  0.022259  0.392891  0.224018  0.781219  0.849157
71  0.189475  0.113061  0.692519  0.309828  0.719433  0.616080  0.875037
72  0.235929  0.296212  0.567986  0.242754  0.629442  0.576344  0.491349
73  0.517754  0.881346  0.906317  0.871352  0.723563  0.380250  0.373828
74  0.492333  0.024214  0.412736  0.910399  0.316882  0.844083  0.665192
75  0.233487  0.818613  0.613034  0.916692  0.979711  0.116452  0.533535
76  0.091288  0.567712  0.774956  0.739897  0.575949  0.260332  0.370284
77  0.616566  0.131445  0.555487  0.084461  0.984911  0.954757  0.574870
78  0.313740  0.085087  0.478999  0.322799  0.315371  0.550377  0.892453
79  0.340236  0.961503  0.317588  0.696962  0.709994  0.051399  0.193384
80  0.613627  0.299230  0.811927  0.854556  0.619628  0.418820  0.953489
81  0.991212  0.576472  0.938855  0.018008  0.200907  0.211972  0.780343
82  0.000669  0.400239  0.623958  0.970433  0.371076  0.463261  0.281863
83  0.120058  0.853315  0.681282  0.092710  0.805066  0.683951  0.801158
84  0.048992  0.076901  0.048416  0.683534  0.132624  0.786024  0.215061
85  0.077440  0.930108  0.723336  0.647833  0.212103  0.513675  0.712062
86  0.775435  0.071420  0.016575  0.202457  0.254097  0.982775  0.633854
87  0.707032  0.049290  0.346989  0.848402  0.344935  0.711849  0.190205
88  0.436244  0.483080  0.711786  0.947644  0.634151  0.595593  0.067152
89  0.075425  0.243642  0.117634  0.554351  0.787128  0.907413  0.858113
90  0.381601  0.533076  0.379682  0.545352  0.388471  0.375217  0.466865
91  0.141758  0.438007  0.462747  0.728428  0.133155  0.996985  0.559517
92  0.107690  0.308030  0.440293  0.054570  0.938655  0.619836  0.156481
93  0.817254  0.830162  0.796738  0.157329  0.596368  0.293758  0.602505
94  0.219970  0.100454  0.609239  0.009087  0.895714  0.071497  0.111025
95  0.084463  0.205167  0.229649  0.026240  0.369234  0.559911  0.609069
96  0.226973  0.528128  0.033160  0.230241  0.727124  0.061222  0.256836
97  0.774824  0.344792  0.338146  0.307326  0.978509  0.502145  0.314932
98  0.909397  0.018248  0.485990  0.732094  0.376599  0.652977  0.273553
99  0.329201  0.293685  0.899018  0.325441  0.694000  0.285630  0.320590

           H         I         J  ...         Q         R         S         T  \
0   0.517397  0.058434  0.026686  ...  0.236908  0.038958  0.131788  0.123735
1   0.523976  0.901227  0.702313  ...  0.859049  0.787451  0.791505  0.865475
2   0.887393  0.610309  0.576252  ...  0.432144  0.810649  0.852810  0.061981
3   0.587999  0.128541  0.906395  ...  0.967175  0.372461  0.561054  0.818201
4   0.783072  0.127892  0.045649  ...  0.207649  0.684989  0.201517  0.479473
5   0.902531  0.845002  0.562014  ...  0.616195  0.541225  0.476107  0.320308
6   0.139254  0.850408  0.809266  ...  0.348701  0.897682  0.216272  0.146244
7   0.196351  0.519582  0.620432  ...  0.325577  0.541674  0.080396  0.982739
8   0.178354  0.902218  0.273029  ...  0.422541  0.378044  0.237055  0.668138
9   0.720725  0.024545  0.767999  ...  0.265870  0.020368  0.715381  0.332594
10  0.908209  0.249226  0.912795  ...  0.585715  0.086659  0.915540  0.916757
11  0.190339  0.183265  0.122051  ...  0.322837  0.309607  0.664439  0.860808
12  0.426425  0.883676  0.412213  ...  0.344343  0.458670  0.025991  0.262594
13  0.555807  0.337086  0.508367  ...  0.290762  0.365165  0.531142  0.543531
14  0.522874  0.047278  0.141544  ...  0.964038  0.750577  0.285906  0.885435
15  0.328971  0.754076  0.052846  ...  0.192708  0.748510  0.453726  0.382713
16  0.940369  0.633653  0.242697  ...  0.863803  0.283269  0.598614  0.241050
17  0.390205  0.413720  0.130019  ...  0.995829  0.498862  0.785709  0.478146
18  0.459722  0.141821  0.114567  ...  0.118462  0.105496  0.143362  0.661369
19  0.000691  0.466153  0.093646  ...  0.659832  0.449503  0.018825  0.855354
20  0.370753  0.319892  0.026118  ...  0.144520  0.998259  0.920810  0.921485
21  0.097424  0.877391  0.430850  ...  0.185762  0.209207  0.826290  0.051248
22  0.698466  0.101614  0.729800  ...  0.652400  0.302651  0.466457  0.675001
23  0.012991  0.537626  0.558183  ...  0.619083  0.901205  0.874742  0.484021
24  0.881440  0.699126  0.024029  ...  0.900233  0.458215  0.641180  0.531582
25  0.260921  0.165916  0.581688  ...  0.815936  0.950394  0.500648  0.684512
26  0.306615  0.409116  0.825198  ...  0.169216  0.787279  0.660553  0.015103
27  0.833957  0.143986  0.248690  ...  0.787734  0.868709  0.710922  0.852870
28  0.097028  0.402889  0.510833  ...  0.667347  0.552728  0.382789  0.753800
29  0.783222  0.124764  0.076351  ...  0.875982  0.960153  0.978390  0.681301
..       ...       ...       ...  ...       ...       ...       ...       ...
70  0.649013  0.153929  0.076076  ...  0.048365  0.370338  0.226476  0.764645
71  0.797269  0.899091  0.434728  ...  0.642207  0.475413  0.729410  0.919014
72  0.096915  0.993109  0.658997  ...  0.929789  0.105735  0.695582  0.124365
73  0.520251  0.482649  0.202184  ...  0.660077  0.204506  0.725946  0.000251
74  0.032841  0.137791  0.802071  ...  0.419413  0.291466  0.046096  0.118457
75  0.648742  0.385050  0.052247  ...  0.235040  0.647567  0.780234  0.535751
76  0.547985  0.914470  0.470482  ...  0.724117  0.073384  0.968448  0.865044
77  0.169973  0.546572  0.896017  ...  0.811312  0.941460  0.782917  0.022992
78  0.312908  0.243417  0.040657  ...  0.611576  0.405278  0.088945  0.798660
79  0.951575  0.670673  0.498666  ...  0.922689  0.209500  0.282514  0.934474
80  0.315048  0.261824  0.820722  ...  0.934988  0.331690  0.932411  0.907396
81  0.322185  0.286874  0.183074  ...  0.105635  0.069450  0.374287  0.179120
82  0.493163  0.071250  0.370776  ...  0.201226  0.655163  0.518981  0.124880
83  0.164722  0.242440  0.029563  ...  0.507589  0.362143  0.543004  0.096268
84  0.777670  0.160052  0.972806  ...  0.642385  0.325295  0.623985  0.109626
85  0.872782  0.005430  0.260178  ...  0.841612  0.986260  0.624932  0.161105
86  0.508218  0.171572  0.257145  ...  0.888694  0.345036  0.392767  0.864358
87  0.798801  0.388542  0.004230  ...  0.649348  0.776391  0.275165  0.868763
88  0.242112  0.576670  0.788759  ...  0.409253  0.013034  0.737293  0.393670
89  0.752310  0.102256  0.330604  ...  0.156633  0.413185  0.571638  0.939368
90  0.357369  0.150742  0.908407  ...  0.943334  0.726781  0.160993  0.608843
91  0.060090  0.857482  0.113510  ...  0.961442  0.228762  0.706308  0.743251
92  0.816167  0.983636  0.575162  ...  0.093647  0.122474  0.213174  0.248880
93  0.179055  0.524891  0.069462  ...  0.972091  0.056830  0.572385  0.892328
94  0.259534  0.452849  0.059253  ...  0.643119  0.095688  0.238118  0.667994
95  0.219062  0.222527  0.871244  ...  0.612749  0.275815  0.104219  0.420030
96  0.839281  0.912886  0.206670  ...  0.572750  0.801136  0.044889  0.502684
97  0.726788  0.753553  0.013071  ...  0.773160  0.563038  0.617658  0.269583
98  0.857156  0.473200  0.436808  ...  0.426618  0.701171  0.852077  0.297119
99  0.443622  0.000386  0.775363  ...  0.197432  0.754886  0.345312  0.809806

           U         V         W         X         Y         Z
0   0.242425  0.348628  0.988460  0.640831  0.865709  0.843608
1   0.406195  0.869410  0.564982  0.860738  0.354139  0.477052
2   0.251011  0.226556  0.172647  0.552415  0.644679  0.299410
3   0.971951  0.619821  0.620485  0.151619  0.759025  0.389631
4   0.299751  0.281602  0.321630  0.489000  0.750280  0.144478
5   0.004254  0.265879  0.523073  0.948858  0.542817  0.925023
6   0.607554  0.226574  0.695173  0.064486  0.894479  0.220246
7   0.526975  0.544361  0.202382  0.906910  0.174538  0.468759
8   0.000973  0.458200  0.070958  0.642147  0.425041  0.021958
9   0.378548  0.629376  0.461920  0.058593  0.920436  0.124989
10  0.162710  0.185088  0.959016  0.086251  0.708105  0.858397
11  0.912116  0.691758  0.448871  0.040680  0.983471  0.750827
12  0.271825  0.787441  0.847070  0.090901  0.339676  0.301082
13  0.223459  0.907308  0.667877  0.269058  0.358881  0.333892
14  0.878738  0.104855  0.165160  0.273940  0.882650  0.129635
15  0.927701  0.316042  0.525681  0.518497  0.386206  0.893704
16  0.817341  0.756866  0.725815  0.404446  0.408595  0.617932
17  0.505107  0.003583  0.772771  0.457166  0.429303  0.036619
18  0.883920  0.320788  0.938730  0.564251  0.227251  0.811595
19  0.441646  0.230458  0.801809  0.603578  0.347271  0.686450
20  0.947704  0.774778  0.911961  0.124913  0.714696  0.503574
21  0.446953  0.686637  0.978788  0.354557  0.089201  0.961636
22  0.732897  0.940221  0.908301  0.285394  0.511473  0.657080
23  0.356845  0.971833  0.061162  0.331077  0.420564  0.749039
24  0.940884  0.069936  0.012809  0.577485  0.413113  0.194992
25  0.032559  0.254286  0.571098  0.992624  0.769782  0.126836
26  0.261571  0.711422  0.129533  0.523801  0.211859  0.680682
27  0.056726  0.199680  0.451365  0.470605  0.057724  0.485176
28  0.297968  0.928276  0.484074  0.151626  0.183526  0.859856
29  0.582722  0.481423  0.643331  0.314335  0.634120  0.925328
..       ...       ...       ...       ...       ...       ...
70  0.922671  0.299091  0.644220  0.913298  0.272536  0.941642
71  0.931335  0.456443  0.037539  0.587083  0.644791  0.437112
72  0.660944  0.145570  0.070477  0.154527  0.687589  0.795704
73  0.783644  0.932564  0.791269  0.005016  0.232739  0.818427
74  0.559153  0.779974  0.571911  0.130456  0.753261  0.554826
75  0.221219  0.052850  0.241413  0.815688  0.718181  0.821998
76  0.915198  0.961301  0.642903  0.520745  0.887126  0.901790
77  0.785627  0.267126  0.348833  0.732608  0.320516  0.520978
78  0.763251  0.250292  0.291829  0.051658  0.247349  0.300586
79  0.733963  0.754155  0.069563  0.295473  0.569891  0.079450
80  0.900609  0.248541  0.590673  0.880438  0.510999  0.542227
81  0.925395  0.391390  0.677707  0.818606  0.011553  0.995503
82  0.667400  0.524003  0.882910  0.187729  0.561612  0.987975
83  0.900329  0.297428  0.278838  0.447836  0.764259  0.110271
84  0.021477  0.326527  0.430374  0.968859  0.705340  0.252136
85  0.066208  0.888942  0.356608  0.151579  0.150800  0.062363
86  0.164239  0.063372  0.533558  0.669441  0.747835  0.858789
87  0.464212  0.436018  0.803799  0.752741  0.456791  0.673260
88  0.387225  0.852139  0.320436  0.840624  0.594794  0.944996
89  0.873294  0.839614  0.358153  0.282672  0.406353  0.460306
90  0.246647  0.578866  0.291841  0.250271  0.322911  0.894520
91  0.276479  0.789752  0.741170  0.813022  0.137316  0.729335
92  0.392615  0.744993  0.434211  0.297699  0.493796  0.872620
93  0.537389  0.262253  0.733142  0.964244  0.258905  0.962174
94  0.748343  0.085625  0.588871  0.025883  0.773421  0.215784
95  0.260045  0.122518  0.449927  0.155399  0.543272  0.557089
96  0.545344  0.450993  0.151896  0.370509  0.021557  0.249583
97  0.037664  0.963414  0.965226  0.142608  0.855216  0.767764
98  0.904426  0.951939  0.835217  0.142012  0.819535  0.769969
99  0.396988  0.402543  0.438482  0.120568  0.371045  0.933880

[100 rows x 26 columns]

In [98]:
# reading a dataframe from a file
mydf = pd.read_csv('z100x26.txt',sep="\t")
mydf.shape

(100, 27)